### ISSUE TITLE
bestgems.org site not updating 

### ISSUE THREAD

**Issue by aithscel** [xmisao/bestgems.org#129]
Hello xmisao

seems like the bestgems site is not updating gems stats.
Not sure if it's all gems or only some. At least [mine](https://bestgems.org/gems/safrano) did not update since a few days.

**Comment by xmisao** [comment]
@aithscel Thank you for your report.

We are currently investigating the issue.

The reason BestGems is not updating is because it fails to retrieve data from RubyGems.

BestGems scrapes the list of gems from RubyGems. However, only the following page causes 500 error:

https://rubygems.org/gems?letter=H&page=73

Strangely enough, the pages before and after it are accessible:

https://rubygems.org/gems?letter=H&page=72
https://rubygems.org/gems?letter=H&page=74

There might be a problematic gem on RubyGems that is causing this issue.

**Comment by xmisao** [comment]
This issue was already fixed in August, so I'll close it now. Thanks for reporting it.
