### ISSUE TITLE
gateway timeout

### ISSUE THREAD

**Issue by phoet** [xmisao/bestgems.org#17]
it looks like the page takes too long to render

<img width="376" alt="screen shot 2016-12-16 at 21 06 26" src="https://cloud.githubusercontent.com/assets/48745/21276824/88530eb4-c3d3-11e6-8365-2ae6e79f2f5b.png">

**Comment by xmisao** [comment]
Hello, phoet.
It has been a long time since we last contacted each other.

Would you try access again?
If you encount same error, please tell me a URL.

I think that this is a temporary problem caused by lacking of server's resource.
I received an alert by the monitoring system.
The BestGems was unavailable in while from 12/17 04:08 to 05:53 in JST(UTC+09:00).

Recently the BestGems is sometimes unstable, and I'm considering measures.

**Comment by phoet** [comment]
i tried a couple of urls all resulting in a timeout. the page is responsive again, so i'll close this issue again. thx!
